// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fengshui.Entity.DBContext;

namespace fengshui.Entity.Migrations
{
    [DbContext(typeof(FengShuiDBContext))]
    partial class FengShuiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("fengshui.Entity.Models.MobileNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceProvider")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("MobileNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 6, 13, 10, 31, 14, 724, DateTimeKind.Local).AddTicks(5722),
                            LastUpdateDate = new DateTime(2021, 6, 13, 10, 31, 14, 725, DateTimeKind.Local).AddTicks(6743),
                            PhoneNumber = "0971111112",
                            ServiceProvider = "Viettel"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2021, 6, 13, 10, 31, 14, 725, DateTimeKind.Local).AddTicks(7496),
                            LastUpdateDate = new DateTime(2021, 6, 13, 10, 31, 14, 725, DateTimeKind.Local).AddTicks(7511),
                            PhoneNumber = "0971111113",
                            ServiceProvider = "Viettel"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2021, 6, 13, 10, 31, 14, 725, DateTimeKind.Local).AddTicks(7521),
                            LastUpdateDate = new DateTime(2021, 6, 13, 10, 31, 14, 725, DateTimeKind.Local).AddTicks(7522),
                            PhoneNumber = "0971111115",
                            ServiceProvider = "Viettel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
